Revert "[open][neva_upstreamable][media][custom] Implement camera player"
:Release Notes:
This reverts commit b290d009eeda8299ae58c702861d4c0f4161b239.

:Detailed Notes:
This causes qemux86 build to fail:
| obj/media/blink/neva/webos/webos/mediaplayerneva_factory_webos.o:
mediaplayerneva_factory_webos.cc:function
media::MediaPlayerNevaFactory::CreateMediaPlayerNeva(
media::MediaPlayerNevaClient*, std::__cxx11::basic_string<char,
std::char_traits<char>, std::allocator<char> > const&,
scoped_refptr<base::SingleThreadTaskRunner> const&): error:
undefined reference to 'media::MediaPlayerCamera::MediaPlayerCamera(media::
MediaPlayerNevaClient*,scoped_refptr<base::SingleThreadTaskRunner> const&)'

:Testing Performed:

:QA Notes:
Test-cases: N/A

:Issues Addressed:

Change-Id: I80c55156dabd3d98581ac4e9cfcd6b7450d82f6f
Reviewed-on: http://gpro.lgsvl.com/230657
Reviewed-by: Lokesh Kumar Goel <lokeshkumar.goel@lge.com>
Tested-by: Lokesh Kumar Goel <lokeshkumar.goel@lge.com>