squash! [BACKPORT] Add PlatformScreen interface in Ozone.
Add missing include. Fixes build for WebOSE which failed with:

../../../../../../../../chromium68/src/content/shell/browser/shell_platform_data_aura.cc: In constructor 'content::ShellPlatformDataAura::ShellPlatformDataAura(const gfx::Size&)':
../../../../../../../../chromium68/src/content/shell/browser/shell_platform_data_aura.cc:76:32: error: 'ui::OzonePlatform' has not been declared
     auto platform_screen = ui::OzonePlatform::GetInstance()->CreateScreen();
                                ^~~~~~~~~~~~~