Revert "[open][neva_upstreamable][a11y] Fix error text readout in network error page"
:Release Notes:
This reverts commit 2a41a04e76c41479640e46bab95f3a961272de94.

:Detailed Notes:
Some of the previous patches missing that cause build error:
| ./../../git/src/content/renderer/render_view_impl.cc:1068:13:
| error: 'class blink::WebSettings' has no member named 'SetAudioGuidanceOn'
|    settings->SetAudioGuidanceOn(prefs.audio_guidance_on);

:Testing Performed:
Build checked

:QA Notes:
Test-cases: N/A

:Issues Addressed:

Change-Id: I761f4b702b9ba5febb02111aac70fc20018598d2
Reviewed-on: http://gpro.lgsvl.com/232504
Reviewed-by: Lokesh Kumar Goel <lokeshkumar.goel@lge.com>
Tested-by: Lokesh Kumar Goel <lokeshkumar.goel@lge.com>